import Head from "next/head";
import { FC } from "react";

export const Header: FC = () => {
  return (
    <Head>
      <title>Next</title>
      <meta name="description" content="Generated by create next app"/>
      <link rel="icon" href="/favicon.ico"/>
    </Head>
  )
}
